### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by jessefulton** [Tschoepler/OHM2Resolume#1]
Is there anything special that needs to be done to get this running? When I open the patch, I get a lot of errors in the Max window. It looks like I might be missing some external libraries or the file is expecting to be in a particular location?

(OSX 10.8.5, Max5, OhmRGB v0.66 firmware)

**Comment by Tschoepler** [comment]
Hi,

sorry for the very late reply. I haven't had the time/chance to adapt the patch to the OhmRGB, yet. But I just recently had time to fix a couple of major bugs and the next step will be implementing the OhmRGB. I will gladly add you to a mailing list that I set up for any news on this feature. Just send me your contact and I will get back to you on this asap.

The patch makes use of some 3rd party externals, but they "ship" with the patch (folder "OHM64 Externals"). They are thr, thru, toxine, idx, _.mxo, OpenSoundControl.
